"use client";

import { FileText, Calendar, MapPin, User, Zap, Building2 } from "lucide-react";
import type { Project } from "@/types";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
export interface CoverPageProps {
  project: Project;
  companyName?: string;
  companyLogoUrl?: string;
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

/** ProCal orange lightning-bolt logo mark */
function LogoMark({ className = "" }: { className?: string }) {
  return (
    <svg
      width="48"
      height="48"
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
      className={className}
    >
      <path
        d="M13 2L4.5 13.5H11L10 22L19.5 10H13L13 2Z"
        fill="#ea580c"
        stroke="#ea580c"
        strokeWidth="1.2"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/** Formatted metadata row */
function MetaRow({
  icon: Icon,
  label,
  value,
}: {
  icon: React.ElementType;
  label: string;
  value: React.ReactNode;
}) {
  return (
    <div className="flex items-start gap-3 text-[13px]">
      <Icon size={16} className="mt-0.5 flex-shrink-0 text-orange-600" />
      <div>
        <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-500">
          {label}
        </p>
        <p className="font-medium text-gray-900">{value || "—"}</p>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Cover Page
// ---------------------------------------------------------------------------
export default function CoverPage({
  project,
  companyName,
  companyLogoUrl,
}: CoverPageProps) {
  const displayLogo = project.logoUrl || companyLogoUrl;
  const displayCompany = companyName || "ProCal Engineering";
  const reportDate = project.date || new Date().toLocaleDateString();

  return (
    <section
      aria-label="Report cover page"
      className="cover-page relative flex flex-col justify-between bg-white text-gray-900"
      style={{
        minHeight: "257mm", // A4 body area minus margins, keeps content inside page
        padding: "10mm",
      }}
    >
      {/* Top brand bar */}
      <div className="flex items-center justify-between border-b-2 border-orange-500 pb-4">
        <div className="flex items-center gap-3">
          <LogoMark />
          <div>
            <p className="text-lg font-bold tracking-tight text-orange-600">
              {displayCompany}
            </p>
            <p className="text-[10px] font-semibold uppercase tracking-widest text-gray-500">
              Electrical Design Report
            </p>
          </div>
        </div>
        {displayLogo && (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={displayLogo}
            alt={`${displayCompany} logo`}
            className="h-14 w-auto object-contain"
          />
        )}
      </div>

      {/* Center title block */}
      <div className="flex-1 flex flex-col items-center justify-center text-center my-8">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-50 border border-orange-200 text-[10px] font-semibold uppercase tracking-widest text-orange-700 mb-5">
          <FileText size={12} />
          Project Report
        </div>
        <h1 className="text-3xl md:text-4xl font-extrabold text-gray-900 leading-tight max-w-3xl">
          {project.name}
        </h1>
        <p className="text-base text-gray-600 mt-3 max-w-2xl">
          Electrical design documentation including load summary, bill of
          materials, MDB schedule, cable schedule, breaker schedule, and voltage
          drop analysis.
        </p>
      </div>

      {/* Metadata grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 border-t border-gray-200 pt-5">
        <MetaRow icon={Building2} label="Client" value={project.client} />
        <MetaRow icon={User} label="Engineer" value={project.engineer} />
        <MetaRow icon={MapPin} label="Location" value={project.location} />
        <MetaRow icon={Calendar} label="Date" value={reportDate} />
        <MetaRow icon={Zap} value={`${project.voltage}V / ${project.frequency}Hz`} label="System" />
        <MetaRow
          icon={FileText}
          label="Buildings"
          value={project.buildings.map((b) => b.name).join(", ")}
        />
      </div>

      {/* Bottom right company mark / disclaimer */}
      <div className="mt-6 pt-4 border-t border-gray-200 text-[10px] text-gray-500 leading-relaxed">
        Generated by ProCal. Values are based on design inputs and standard
        electrical calculation methods; verify all field installation details
        against local regulations and project specifications.
      </div>
    </section>
  );
}
